export const colors = {
  primary: '#0038d1',
  onPrimary: '#ffffff',
  primaryContainer: '#2f54eb',
  onPrimaryContainer: '#dee1ff',
  tertiaryContainer: '#b33d00',
  onTertiaryContainer: '#ffdbcf',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  secondaryContainer: '#d9e0f0',
  onSecondaryContainer: '#5c6370',
  surfaceContainerHigh: '#e8e8e8',
  surfaceContainer: '#eeeeee',
  surfaceContainerLow: '#f3f3f3',
  surfaceContainerLowest: '#ffffff',
  surfaceVariant: '#e2e2e2',
  background: '#f9f9f9',
  onBackground: '#1a1c1c',
  onSurface: '#1a1c1c',
  onSurfaceVariant: '#444655',
  error: '#ba1a1a',
  outline: '#747687',
};
